### ISSUE TITLE
WMbus LoRaWAN: Temperature is little-endian

### ISSUE THREAD

**Issue by h4cc** [lobaro/docs#2]
According to docs this temperature is int16, /10 which results in Celsius. From what i can see from devices, the temperature is send in little endian. 

Example payload: `020500 0E68 8000 00`
`020500` = version 2.5.0
`0E68` = voltage 3,688V
`8000` = -3276C
`00` = flags

When parsing `0080` its 12.8 °C, which seems much more likely.

https://github.com/lobaro/docs/blame/master/docs/lorawan-sensors/wmbus-lorawan/index.md#L343

**Comment by Niondir** [comment]
Thanks for mentioning, I added a comment to the doc.
